### ISSUE TITLE
Size Option

### ISSUE THREAD

**Issue by graywolf336** [ireade/emoj11y#1]
Hey, thanks for this component.

One thing I would like to see added is the ability to have a size option be passed. :)

**Comment by ireade** [comment]
Hi @graywolf336 ! You're welcome :)

You can do that by setting the font-size on the element, since everything within the component is styled using ems.

For example:

```html
<emoj11y-element style="font-size: 20px" shortname="smile"></emoj11y-element>
```

Or using CSS:

```css
.emoj11y-element {
    font-size: 20px
}
```

**Comment by graywolf336** [comment]
Good deal, thanks!
